packageExtensions:
  '@vitest/browser-playwright@*':
    peerDependencies:
      vite: '*'
  '@vitest/browser@*':
    peerDependencies:
      vite: '*'

  'storybook@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      vitest: '*'

  'next@*':
    dependencies:
      '@vanilla-extract/next-plugin': '*'

  '@hookform/resolvers@*':
    peerDependencies:
      zod: '*'
  'zod@*':
    dependencies:
      zod: '*'
